#ifndef SDK_OBSERVERMODE
#define SDK_OBSERVERMODE

enum class ObserverMode : int {
	OBS_MODE_NONE = 0,
	OBS_MODE_DEATHCAM,
	OBS_MODE_FREEZECAM,
	OBS_MODE_FIXED,
	OBS_MODE_IN_EYE,
	OBS_MODE_CHASE,
	OBS_MODE_ROAMING
};

#endif
