#include "Features.hpp"

BEGIN_SERIALIZED_STRUCT(Features::General::Serializer, xorstr_("General"))
SERIALIZED_NAMESPACE(Menu)
SERIALIZED_NAMESPACE(Watermark)
SERIALIZED_NAMESPACE(EnginePrediction)
SERIALIZED_NAMESPACE(EventLog)
END_SERIALIZED_STRUCT

BEGIN_SERIALIZED_STRUCT(Features::Legit::Serializer, xorstr_("Legit"))
SERIALIZED_NAMESPACE(Aimbot)
SERIALIZED_NAMESPACE(Triggerbot)
END_SERIALIZED_STRUCT

BEGIN_SERIALIZED_STRUCT(Features::Semirage::Serializer, xorstr_("Semirage"))
SERIALIZED_NAMESPACE(Aimbot)
SERIALIZED_NAMESPACE(Backtrack)
SERIALIZED_NAMESPACE(RecoilAssistance)
END_SERIALIZED_STRUCT

BEGIN_SERIALIZED_STRUCT(Features::Movement::Serializer, xorstr_("Movement"))
SERIALIZED_NAMESPACE(Bhop)
SERIALIZED_NAMESPACE(CrouchJump)
SERIALIZED_NAMESPACE(JumpBug)
SERIALIZED_NAMESPACE(EdgeJump)
SERIALIZED_NAMESPACE(AutoStrafer)
SERIALIZED_NAMESPACE(FastDuck)
END_SERIALIZED_STRUCT

BEGIN_SERIALIZED_STRUCT(Features::Visuals::Serializer, xorstr_("Visuals"))
SERIALIZED_NAMESPACE(Esp)
SERIALIZED_NAMESPACE(SpectatorList)
SERIALIZED_NAMESPACE(NoPunch)
END_SERIALIZED_STRUCT

BEGIN_SERIALIZED_STRUCT(Features::Serializer, xorstr_("Features"))
SERIALIZED_NAMESPACE(General)
SERIALIZED_NAMESPACE(Legit)
SERIALIZED_NAMESPACE(Semirage)
SERIALIZED_NAMESPACE(Movement)
SERIALIZED_NAMESPACE(Visuals)
END_SERIALIZED_STRUCT
